<!-- GitHub Star -->
<iframe src="https://ghbtns.com/github-btn.html?user=zeroby0&type=follow" frameborder="0" scrolling="0" width="120px" height="20px"></iframe>

<!-- Twitter follow button -->
<a href="https://twitter.com/4ravind" class="twitter-follow-button" data-show-count="false">Follow @4aravind</a>
<script>
window.twttr=(function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],t=window.twttr||{};if(d.getElementById(id))return;js=d.createElement(s);js.id=id;js.src="https://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);t._e=[];t.ready=function(f){t._e.push(f);};return t;}(document,"script","twitter-wjs"));
</script>
